### ISSUE TITLE
"This method cannot be called from the event loop thread" when calling a function inside a Pod spec

### ISSUE THREAD

**Issue by cpressland** [kr8s-org/kr8s#190]
### Which project are you reporting a bug for?

kr8s

### What happened?

Following the fixes applied in #183 a new bug has appeared.

Traceback: 
```
Traceback (most recent call last):
  File "/Users/cpressland/dev/starbug/loop.py", line 27, in <module>
    "value": get_secret_value("azure-storage", "account_name"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/dev/starbug/loop.py", line 8, in get_secret_value
    secret = Secret.get(name=name, namespace=namespace)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/dev/starbug/.venv/lib/python3.11/site-packages/kr8s/_io.py", line 75, in wrapped
    return portal.call(wrapped)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/dev/starbug/.venv/lib/python3.11/site-packages/kr8s/_io.py", line 50, in call
    return self._portal.call(func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/dev/starbug/.venv/lib/python3.11/site-packages/anyio/from_thread.py", line 277, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/cpressland/dev/starbug/.venv/lib/python3.11/site-packages/anyio/from_thread.py", line 217, in _call_func
    retval = await retval
             ^^^^^^^^^^^^
  File "/Users/cpressland/dev/starbug/.venv/lib/python3.11/site-packages/kr8s/_objects.py", line 170, in get
    api = kr8s.api()
          ^^^^^^^^^^
  File "/Users/cpressland/dev/starbug/.venv/lib/python3.11/site-packages/kr8s/_io.py", line 75, in wrapped
    return portal.call(wrapped)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/dev/starbug/.venv/lib/python3.11/site-packages/kr8s/_io.py", line 50, in call
    return self._portal.call(func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/dev/starbug/.venv/lib/python3.11/site-packages/anyio/from_thread.py", line 277, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/dev/starbug/.venv/lib/python3.11/site-packages/anyio/from_thread.py", line 362, in start_task_soon
    self._check_running()
  File "/Users/cpressland/dev/starbug/.venv/lib/python3.11/site-packages/anyio/from_thread.py", line 174, in _check_running
    raise RuntimeError(
RuntimeError: This method cannot be called from the event loop thread
```

Sample code:

```python
from base64 import b64decode

from kr8s.objects import Pod, Secret


def get_secret_value(name: str, key: str, namespace: str = "default") -> str:
    """Get the Value of a Secret."""
    secret = Secret.get(name=name, namespace=namespace)
    return b64decode(secret.raw["data"][key]).decode("utf-8")


my_pod = Pod({
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "name": "my-pod",
        "namespace": "default",
    },
    "spec": {
        "containers": [
            {
                "name": "my-container",
                "image": "docker.io/ubuntu:latest",
                "env": [
                    {
                        "name": "MY_ENV_VAR",
                        "value": get_secret_value("azure-storage", "account_name"),
                    },
                ],
            },
        ],
    },
})

my_pod.create()
```

### Anything else?

When downgrading back to version `0.9.0` this code works just fine.

**Comment by jacobtomlinson** [comment]
Thanks for raising this. It looks like this happens when simply calling `APIObject.get`. Here's a smaller reproducer we can use to debug. I'll investigate.

```python
from kr8s.objects import Secret
Secret.get("foo")
```

```pytb
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[8], line 1
----> 1 Service.get("foo")

File ~/Projects/kr8s-org/kr8s/kr8s/_io.py:75, in run_sync.<locals>.wrapped(*args, **kwargs)
     73 portal = Portal()
     74 if inspect.iscoroutinefunction(coro):
---> 75     return portal.call(wrapped)
     76 raise TypeError(f"Expected coroutine function, got {coro.__class__.__name__}")

File ~/Projects/kr8s-org/kr8s/kr8s/_io.py:50, in Portal.call(self, func, *args, **kwargs)
     48 while not self._portal:
     49     pass
---> 50 return self._portal.call(func, *args, **kwargs)

File ~/miniconda3/envs/kr8s/lib/python3.10/site-packages/anyio/from_thread.py:277, in BlockingPortal.call(self, func, *args)
    264 def call(
    265     self, func: Callable[..., Awaitable[T_Retval] | T_Retval], *args: object
    266 ) -> T_Retval:
    267     """
    268     Call the given function in the event loop thread.
    269 
   (...)
    275 
    276     """
--> 277     return cast(T_Retval, self.start_task_soon(func, *args).result())

File ~/miniconda3/envs/kr8s/lib/python3.10/concurrent/futures/_base.py:451, in Future.result(self, timeout)
    449     raise CancelledError()
    450 elif self._state == FINISHED:
--> 451     return self.__get_result()
    453 self._condition.wait(timeout)
    455 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File ~/miniconda3/envs/kr8s/lib/python3.10/concurrent/futures/_base.py:403, in Future.__get_result(self)
    401 if self._exception:
    402     try:
--> 403         raise self._exception
    404     finally:
    405         # Break a reference cycle with the exception in self._exception
    406         self = None

File ~/miniconda3/envs/kr8s/lib/python3.10/site-packages/anyio/from_thread.py:217, in BlockingPortal._call_func(self, func, args, kwargs, future)
    214             else:
    215                 future.add_done_callback(callback)
--> 217             retval = await retval
    218 except self._cancelled_exc_class:
    219     future.cancel()

File ~/Projects/kr8s-org/kr8s/kr8s/_objects.py:170, in APIObject.get(cls, name, namespace, api, label_selector, field_selector, timeout, **kwargs)
    168         api = await kr8s.asyncio.api()
    169     else:
--> 170         api = kr8s.api()
    171 namespace = namespace if namespace else api.namespace
    172 start = time.time()

File ~/Projects/kr8s-org/kr8s/kr8s/_io.py:75, in run_sync.<locals>.wrapped(*args, **kwargs)
     73 portal = Portal()
     74 if inspect.iscoroutinefunction(coro):
---> 75     return portal.call(wrapped)
     76 raise TypeError(f"Expected coroutine function, got {coro.__class__.__name__}")

File ~/Projects/kr8s-org/kr8s/kr8s/_io.py:50, in Portal.call(self, func, *args, **kwargs)
     48 while not self._portal:
     49     pass
---> 50 return self._portal.call(func, *args, **kwargs)

File ~/miniconda3/envs/kr8s/lib/python3.10/site-packages/anyio/from_thread.py:277, in BlockingPortal.call(self, func, *args)
    264 def call(
    265     self, func: Callable[..., Awaitable[T_Retval] | T_Retval], *args: object
    266 ) -> T_Retval:
    267     """
    268     Call the given function in the event loop thread.
    269 
   (...)
    275 
    276     """
--> 277     return cast(T_Retval, self.start_task_soon(func, *args).result())

File ~/miniconda3/envs/kr8s/lib/python3.10/site-packages/anyio/from_thread.py:361, in BlockingPortal.start_task_soon(self, func, name, *args)
    338 def start_task_soon(
    339     self,
    340     func: Callable[..., Awaitable[T_Retval] | T_Retval],
    341     *args: object,
    342     name: object = None,
    343 ) -> Future[T_Retval]:
    344     """
    345     Start a task in the portal's task group.
    346 
   (...)
    359 
    360     """
--> 361     self._check_running()
    362     f: Future = Future()
    363     self._spawn_task_from_thread(func, args, {}, name, f)

File ~/miniconda3/envs/kr8s/lib/python3.10/site-packages/anyio/from_thread.py:174, in BlockingPortal._check_running(self)
    172     raise RuntimeError("This portal is not running")
    173 if self._event_loop_thread_id == threading.get_ident():
--> 174     raise RuntimeError(
    175         "This method cannot be called from the event loop thread"
    176     )

RuntimeError: This method cannot be called from the event loop thread

In [9]: from kr8s.objects import Service
   ...: Service.get("foo")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[9], line 2
      1 from kr8s.objects import Service
----> 2 Service.get("foo")

File ~/Projects/kr8s-org/kr8s/kr8s/_io.py:75, in run_sync.<locals>.wrapped(*args, **kwargs)
     73 portal = Portal()
     74 if inspect.iscoroutinefunction(coro):
---> 75     return portal.call(wrapped)
     76 raise TypeError(f"Expected coroutine function, got {coro.__class__.__name__}")

File ~/Projects/kr8s-org/kr8s/kr8s/_io.py:50, in Portal.call(self, func, *args, **kwargs)
     48 while not self._portal:
     49     pass
---> 50 return self._portal.call(func, *args, **kwargs)

File ~/miniconda3/envs/kr8s/lib/python3.10/site-packages/anyio/from_thread.py:277, in BlockingPortal.call(self, func, *args)
    264 def call(
    265     self, func: Callable[..., Awaitable[T_Retval] | T_Retval], *args: object
    266 ) -> T_Retval:
    267     """
    268     Call the given function in the event loop thread.
    269 
   (...)
    275 
    276     """
--> 277     return cast(T_Retval, self.start_task_soon(func, *args).result())

File ~/miniconda3/envs/kr8s/lib/python3.10/concurrent/futures/_base.py:451, in Future.result(self, timeout)
    449     raise CancelledError()
    450 elif self._state == FINISHED:
--> 451     return self.__get_result()
    453 self._condition.wait(timeout)
    455 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File ~/miniconda3/envs/kr8s/lib/python3.10/concurrent/futures/_base.py:403, in Future.__get_result(self)
    401 if self._exception:
    402     try:
--> 403         raise self._exception
    404     finally:
    405         # Break a reference cycle with the exception in self._exception
    406         self = None

File ~/miniconda3/envs/kr8s/lib/python3.10/site-packages/anyio/from_thread.py:217, in BlockingPortal._call_func(self, func, args, kwargs, future)
    214             else:
    215                 future.add_done_callback(callback)
--> 217             retval = await retval
    218 except self._cancelled_exc_class:
    219     future.cancel()

File ~/Projects/kr8s-org/kr8s/kr8s/_objects.py:170, in APIObject.get(cls, name, namespace, api, label_selector, field_selector, timeout, **kwargs)
    168         api = await kr8s.asyncio.api()
    169     else:
--> 170         api = kr8s.api()
    171 namespace = namespace if namespace else api.namespace
    172 start = time.time()

File ~/Projects/kr8s-org/kr8s/kr8s/_io.py:75, in run_sync.<locals>.wrapped(*args, **kwargs)
     73 portal = Portal()
     74 if inspect.iscoroutinefunction(coro):
---> 75     return portal.call(wrapped)
     76 raise TypeError(f"Expected coroutine function, got {coro.__class__.__name__}")

File ~/Projects/kr8s-org/kr8s/kr8s/_io.py:50, in Portal.call(self, func, *args, **kwargs)
     48 while not self._portal:
     49     pass
---> 50 return self._portal.call(func, *args, **kwargs)

File ~/miniconda3/envs/kr8s/lib/python3.10/site-packages/anyio/from_thread.py:277, in BlockingPortal.call(self, func, *args)
    264 def call(
    265     self, func: Callable[..., Awaitable[T_Retval] | T_Retval], *args: object
    266 ) -> T_Retval:
    267     """
    268     Call the given function in the event loop thread.
    269 
   (...)
    275 
    276     """
--> 277     return cast(T_Retval, self.start_task_soon(func, *args).result())

File ~/miniconda3/envs/kr8s/lib/python3.10/site-packages/anyio/from_thread.py:361, in BlockingPortal.start_task_soon(self, func, name, *args)
    338 def start_task_soon(
    339     self,
    340     func: Callable[..., Awaitable[T_Retval] | T_Retval],
    341     *args: object,
    342     name: object = None,
    343 ) -> Future[T_Retval]:
    344     """
    345     Start a task in the portal's task group.
    346 
   (...)
    359 
    360     """
--> 361     self._check_running()
    362     f: Future = Future()
    363     self._spawn_task_from_thread(func, args, {}, name, f)

File ~/miniconda3/envs/kr8s/lib/python3.10/site-packages/anyio/from_thread.py:174, in BlockingPortal._check_running(self)
    172     raise RuntimeError("This portal is not running")
    173 if self._event_loop_thread_id == threading.get_ident():
--> 174     raise RuntimeError(
    175         "This method cannot be called from the event loop thread"
    176     )

RuntimeError: This method cannot be called from the event loop thread
```
