### ISSUE TITLE
Port forwarding not well documented

### ISSUE THREAD

**Issue by aviadkray** [kr8s-org/kr8s#217]
### Which project are you reporting a bug for?

kr8s

### What happened?

I was trying to use the PF feature.
After a lot of digging, i got to this code:

```python
import asyncio
from kr8s.asyncio.portforward import PortForward

async def kpf(pod, rport, lport):
    async with PortForward(pod, rport, lport) as port:
        print(f"Forwarding to port {rport} with local port {lport} on Pod {pod.name}")

from kr8s.objects import Pod

pod = Pod.get("vault-0")

asyncio.run(kpf(pod, 8200, 8200))
```
I can see with ss -nlpt that the port is indeed opened, but no traffic is going through it (both in code, nor with a simple curl command). IMHO, is seems like the traffic is going to the pod, but just not coming back.

BTW, trying to use the "Explict start/stop", just doesn't open the port at all.

Thank you, Aviad.

### Anything else?

The documentation to get this working can be improved.

**Comment by jacobtomlinson** [comment]
I'm guessing something is getting deadlocked due to the mixing of the sync and async APIs in your example.

Here's a working example:

```python
import asyncio
# Make sure we use an async Pod object if we are using the async API
from kr8s.asyncio.objects import Pod

async def run():
    p = await Pod.get("vault-0")
    async with p.portforward(8200, 8200) as port:
        # Let the event loop run all tasks
        while True:
            await asyncio.sleep(60)

asyncio.run(run())
```

Here's the same example using the `start()` method instead of the context manager.

```python
import asyncio
# Make sure we use an async Pod object if we are using the async API
from kr8s.asyncio.objects import Pod

async def run():
    p = await Pod.get("vault-0")
    port = await p.portforward(8200, 8200).start()
    # Let the event loop run all tasks
    while True:
        await asyncio.sleep(3600)

asyncio.run(run())
```

The key things here are to ensure you're using the right object and to give the event loop room the breathe and process all tasks in its queue (there are tasks for passing data back and forth through the pipe).

I totally agree we could do with better documentation on this. I also had a play around with the sync API and discovered a different bug that I'll open a new ticket for.

**Comment by jacobtomlinson** [comment]
Writing out these examples also makes me think that the API could be improved too. It might be nice to add some kind of `run_forever()` method which handles starting the port forward and blocking the event loop for you.

```python
from kr8s.asyncio.objects import Pod

async def run():
    p = await Pod.get("vault-0")
    await p.portforward(8200, 8200).run_forever()

asyncio.run(run())
```

**Comment by aviadkray** [comment]
First of all, this works now and thank you very much :)
I did still have to put this into a thread to be able to do other stuff while the port is open (thank you GPT), so the docs can be extended to reflect this:
```
import asyncio
from kr8s.asyncio.objects import Pod
import threading
# Open port forward to vault
async def run_async_task():
    p = await Pod.get("vault-0")
    port = await p.portforward(8200, 8200).start()
    while True:
        await asyncio.sleep(3600)

def start_asyncio_loop():
    asyncio.run(run_async_task())

# Starting the asyncio loop in a separate thread
thread = threading.Thread(target=start_asyncio_loop, daemon=True)
thread.start()

# Your synchronous code can continue here
print("yey")

```

**Comment by jacobtomlinson** [comment]
I've just fixed up a couple of bugs with the async API so everything should work as designed now, you shouldn't need to worry about creating a background thread as `kr8s` will do that for you.

If you update to `v0.12.1` you should be able to do the following using just the sync API:

```python
from kr8s.objects import Pod

# Open port forward to vault
p = Pod.get("vault-0")
pf = p.portforward(8200, 8200)
pf.start() # Runs the port forward on a background thread

# Your synchronous code can continue here
print("yey")
```

**Comment by aviadkray** [comment]
I have upgraded to v0.12.1, and ran this code:
```
from kr8s.objects import Pod
pod = Pod.get("vault-0")
pf = pod.portforward(remote_port=8200, local_port=8200)
pf.start()
```
It seems to work well, however when issuing the "pf.stop()" method, I get this stacktrace:
```
Exception in thread Thread-6 (run_forever):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aviad/Git/.venv/lib/python3.10/site-packages/kr8s/_io.py", line 75, in wrapped
    return portal.call(wrapped)
  File "/home/aviad/Git/.venv/lib/python3.10/site-packages/kr8s/_io.py", line 50, in call
    return self._portal.call(func, *args, **kwargs)
  File "/home/aviad/Git/.venv/lib/python3.10/site-packages/anyio/from_thread.py", line 277, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 456, in result
    raise CancelledError()
concurrent.futures._base.CancelledError

I am very happy this is progressing so quickly, and that this allows me to completely skip the use of threads when it will be complete.

**Comment by aviadkray** [comment]
on another note, while this doesn't seem to be an issue in VS code's debug/terminal, I am getting the following when running on a regular terminal:
```
future: <Task finished name='Task-59' coro=<PortForward._sync_sockets() done, defined at /home/aviad/.local/lib/python3.10/site-packages/kr8s/_portforward.py:180> exception=ExceptionGroup('unhandled errors in a TaskGroup', [ConnectionClosedError('TCP socket closed')])>
  + Exception Group Traceback (most recent call last):
  |   File "/home/aviad/.local/lib/python3.10/site-packages/kr8s/_portforward.py", line 184, in _sync_sockets
  |     async with anyio.create_task_group() as tg:
  |   File "/home/aviad/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 658, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/aviad/.local/lib/python3.10/site-packages/kr8s/_portforward.py", line 196, in _tcp_to_ws
    |     raise ConnectionClosedError("TCP socket closed")
    | kr8s._exceptions.ConnectionClosedError: TCP socket closed
    +------------------------------------
```
I am not sure if this a "my setup" type of issue, or something else. Thank you.
