### ISSUE TITLE
Portforward "stop" causes a "base" error.

### ISSUE THREAD

**Issue by aviadkray** [kr8s-org/kr8s#221]
### Which project are you reporting a bug for?

kr8s

### What happened?

Moving these comments to an issue.

I have upgraded to v0.12.1, and ran this code:
```python
from kr8s.objects import Pod
pod = Pod.get("vault-0")
pf = pod.portforward(remote_port=8200, local_port=8200)
pf.start()
print("yey")
pf.stop()
```
It seems to work well, as in the port is open and traffic is going through it. However when issuing the "pf.stop()" method, I get this stacktrace:
```pytb
Exception in thread Thread-6 (run_forever):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aviad/Git/.venv/lib/python3.10/site-packages/kr8s/_io.py", line 75, in wrapped
    return portal.call(wrapped)
  File "/home/aviad/Git/.venv/lib/python3.10/site-packages/kr8s/_io.py", line 50, in call
    return self._portal.call(func, *args, **kwargs)
  File "/home/aviad/Git/.venv/lib/python3.10/site-packages/anyio/from_thread.py", line 277, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 456, in result
    raise CancelledError()
concurrent.futures._base.CancelledError
```

On another note, while this doesn't seem to be an issue in VS code's debug/terminal, I am getting the following when running on a regular terminal:
```pytb
future: <Task finished name='Task-59' coro=<PortForward._sync_sockets() done, defined at /home/aviad/.local/lib/python3.10/site-packages/kr8s/_portforward.py:180> exception=ExceptionGroup('unhandled errors in a TaskGroup', [ConnectionClosedError('TCP socket closed')])>
  + Exception Group Traceback (most recent call last):
  |   File "/home/aviad/.local/lib/python3.10/site-packages/kr8s/_portforward.py", line 184, in _sync_sockets
  |     async with anyio.create_task_group() as tg:
  |   File "/home/aviad/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 658, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/aviad/.local/lib/python3.10/site-packages/kr8s/_portforward.py", line 196, in _tcp_to_ws
    |     raise ConnectionClosedError("TCP socket closed")
    | kr8s._exceptions.ConnectionClosedError: TCP socket closed
    +------------------------------------
```
I am very happy this is progressing so quickly, and that this allows me to completely skip the use of threads or any other method to open the port to the pod like invoking kubectl with subporcess that I was using until now, even in its current state.

**Comment by jacobtomlinson** [comment]
Thanks for raising this. I wasn't able to reproduce this with the exact snippet you shared, but I found the warning comes up when calling `pf.start()` again after it has been stopped.

```python
>>> from kr8s.objects import Pod
>>> pod = Pod.get("example-1")
>>> pf = pod.portforward(remote_port=80, local_port=8200)
>>> pf.start()
>>> print("yey")
yey
>>> pf.stop()
>>> print("yey")
yey
>>> pf.start()
Exception in thread Thread-1 (run_forever):
Traceback (most recent call last):
  File "/home/jacob/miniconda3/envs/kr8s/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/jacob/miniconda3/envs/kr8s/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jacob/Projects/kr8s-org/kr8s/kr8s/_io.py", line 75, in wrapped
    return portal.call(wrapped)
  File "/home/jacob/Projects/kr8s-org/kr8s/kr8s/_io.py", line 50, in call
    return self._portal.call(func, *args, **kwargs)
  File "/home/jacob/miniconda3/envs/kr8s/lib/python3.10/site-packages/anyio/from_thread.py", line 277, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
  File "/home/jacob/miniconda3/envs/kr8s/lib/python3.10/concurrent/futures/_base.py", line 456, in result
    raise CancelledError()
concurrent.futures._base.CancelledError
```

I also note that even though we see this exception when starting the portforward the tunnel is still open and I can communicate with the Pod over the forward. This leads me to think this exception is related to the previous tunnel being stopped, but doesn't get raised until the next time we interact with the event loop.

_Also I moved the second exception you mentioned to #223 as I think it's separate, but I haven't been able to reproduce it yet._

**Comment by jacobtomlinson** [comment]
Yup I think my hunch is right because the exception gets printed regardless of what API call I make. It doesn't have to be starting the portforward again.

```python
>>> from kr8s.objects import Pod
>>> pod = Pod.get("example-1")
>>> pf = pod.portforward(remote_port=80, local_port=8200)
>>> pf.start()
>>> pf.stop()
>>> pod.exists()
Exception in thread Thread-1 (run_forever):
Traceback (most recent call last):
  File "/home/jacob/miniconda3/envs/kr8s/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/jacob/miniconda3/envs/kr8s/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jacob/Projects/kr8s-org/kr8s/kr8s/_io.py", line 75, in wrapped
    return portal.call(wrapped)
  File "/home/jacob/Projects/kr8s-org/kr8s/kr8s/_io.py", line 50, in call
    return self._portal.call(func, *args, **kwargs)
  File "/home/jacob/miniconda3/envs/kr8s/lib/python3.10/site-packages/anyio/from_thread.py", line 277, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
  File "/home/jacob/miniconda3/envs/kr8s/lib/python3.10/concurrent/futures/_base.py", line 456, in result
    raise CancelledError()
concurrent.futures._base.CancelledError
```

**Comment by aviadkray** [comment]
Even weirder, is that I have setup the env on a remote Ubuntu vm, and now this doesn't happen at all...
The env this does happen on, is Ubuntu 22.04 under WSL.

**Comment by jacobtomlinson** [comment]
Weird, well I'm catching this stray exception now anyway so this should be resolved.

**Comment by aviadkray** [comment]
still happens on my WSL...
