### ISSUE TITLE
kr8s._exceptions.ConnectionClosedError: TCP socket closed when port forwarding

### ISSUE THREAD

**Issue by jacobtomlinson** [kr8s-org/kr8s#223]
### Which project are you reporting a bug for?

kr8s

### What happened?

> [!NOTE]  
> Pulled out from #221 raised by @aviadkray

On another note, while this doesn't seem to be an issue in VS code's debug/terminal, I am getting the following when running on a regular terminal:
```pytb
future: <Task finished name='Task-59' coro=<PortForward._sync_sockets() done, defined at /home/aviad/.local/lib/python3.10/site-packages/kr8s/_portforward.py:180> exception=ExceptionGroup('unhandled errors in a TaskGroup', [ConnectionClosedError('TCP socket closed')])>
  + Exception Group Traceback (most recent call last):
  |   File "/home/aviad/.local/lib/python3.10/site-packages/kr8s/_portforward.py", line 184, in _sync_sockets
  |     async with anyio.create_task_group() as tg:
  |   File "/home/aviad/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 658, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/aviad/.local/lib/python3.10/site-packages/kr8s/_portforward.py", line 196, in _tcp_to_ws
    |     raise ConnectionClosedError("TCP socket closed")
    | kr8s._exceptions.ConnectionClosedError: TCP socket closed
    +------------------------------------
```

**Comment by aviadkray** [comment]
Actually i got it to reproduce in VS code when using the remote-ssh extension.
I was setting up the env on a remote Ubuntu vm, for this issue, and now it shows up.
The code that tripped it was:
```
def check_for_204_response(response, url = "", headers = "", payload_json = ""):
    if response.status_code == 204:
        state = "Sucsseseded"
    else:
        state = "Failed"
    print(f"{state} issuing {url=} with {headers=} and {payload_json=}. Status code: {response.status_code} and {response=}")

# Delete the current vault mount
url = "http://localhost:8200/v1/sys/mounts/kd"
headers = {
    "X-Vault-Token": vault_token,
}
# Send a DELETE request
response = requests.delete(url, headers=headers)
# Check the response status code
check_for_204_response(response, url, headers)
```

Please ask more questions

**Comment by jacobtomlinson** [comment]
Does it happen consistently in the same place if you run that code over and over?

**Comment by jacobtomlinson** [comment]
Do you know if this medusa tool is making one large request or lots of small requests?

**Comment by aviadkray** [comment]
I'm sorry, i don't know...
it here if you want to examine it...
https://github.com/jonasvinther/medusa

**Comment by jacobtomlinson** [comment]
@aviadkray I got to the bottom of this so with the latest `v0.12.10` this noisy warning should go away.
