### ISSUE TITLE
Unable to fetch namespaces if metrics service is unavailable at this moment

### ISSUE THREAD

**Issue by stanislavhordiyenko** [kr8s-org/kr8s#230]
### Which project are you reporting a bug for?

kr8s

### What happened?

```kr8s==0.12.3```

I am not able to fetch all namespaces, if some API are not working at this moment i.e. metrics.

At this moment, `kubectl` returns me this error: `E1205 15:53:39.605236   31092 memcache.go:287] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request` but still able to return namespaces.

But, `kr8s` itself cannot fetch namespaces, if metrics service is unavailable. The same happened to me in another environment, where linkerd doesn't work.

**Comment by stanislavhordiyenko** [comment]
@jacobtomlinson I installed a dev version of kr8s. `pip list` confirmed I am on a dev version `0.12.4.dev1+g95e5d49`.

Then, I ran my code again, and it failed. I chose environment, where linkerd is not functioning properly and got the same exception. Here it is:
```
Traceback (most recent call last):
  File "/Users/stanislav.hordiyenko/Desktop/sandbox/k8s-resource-audit/main.py", line 9, in <module>
    for ns in kr8s.get("namespaces"):
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stanislav.hordiyenko/Desktop/sandbox/k8s-resource-audit/venv/lib/python3.11/site-packages/kr8s/__init__.py", line 90, in get
    return _run_sync(partial(_get, _asyncio=False))(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stanislav.hordiyenko/Desktop/sandbox/k8s-resource-audit/venv/lib/python3.11/site-packages/kr8s/_io.py", line 75, in wrapped
    return portal.call(wrapped)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/stanislav.hordiyenko/Desktop/sandbox/k8s-resource-audit/venv/lib/python3.11/site-packages/kr8s/_io.py", line 50, in call
    return self._portal.call(func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stanislav.hordiyenko/Desktop/sandbox/k8s-resource-audit/venv/lib/python3.11/site-packages/anyio/from_thread.py", line 266, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/stanislav.hordiyenko/Desktop/sandbox/k8s-resource-audit/venv/lib/python3.11/site-packages/anyio/from_thread.py", line 203, in _call_func
    retval = await retval
             ^^^^^^^^^^^^
  File "/Users/stanislav.hordiyenko/Desktop/sandbox/k8s-resource-audit/venv/lib/python3.11/site-packages/kr8s/asyncio/_helpers.py", line 65, in get
    return await api._get(
           ^^^^^^^^^^^^^^^
  File "/Users/stanislav.hordiyenko/Desktop/sandbox/k8s-resource-audit/venv/lib/python3.11/site-packages/kr8s/_api.py", line 337, in _get
    async with self._get_kind(
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stanislav.hordiyenko/Desktop/sandbox/k8s-resource-audit/venv/lib/python3.11/site-packages/kr8s/_api.py", line 257, in _get_kind
    resources = await self._api_resources()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stanislav.hordiyenko/Desktop/sandbox/k8s-resource-audit/venv/lib/python3.11/site-packages/kr8s/_api.py", line 427, in _api_resources
    async with self.call_api(
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stanislav.hordiyenko/Desktop/sandbox/k8s-resource-audit/venv/lib/python3.11/site-packages/kr8s/_api.py", line 136, in call_api
    response.raise_for_status()
  File "/Users/stanislav.hordiyenko/Desktop/sandbox/k8s-resource-audit/venv/lib/python3.11/site-packages/httpx/_models.py", line 758, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '503 Service Unavailable' for url 'https://35.189.1.155/apis/tap.linkerd.io/v1alpha1'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
```

**Comment by stanislavhordiyenko** [comment]
`kubectl` returns me this information before returning actual results:
```
E1206 08:42:53.228971   34750 memcache.go:287] couldn't get resource list for tap.linkerd.io/v1alpha1: the server is currently unable to handle the request
```

**Comment by jacobtomlinson** [comment]
Ah I missed something, mind installing from that branch again and trying again?

**Comment by stanislavhordiyenko** [comment]
One moment..

**Comment by stanislavhordiyenko** [comment]
Now, it works. I can see that it also reports about the issue in the beginning like `kubectl`:
```
/Users/stanislav.hordiyenko/Desktop/sandbox/k8s-resource-audit/venv/lib/python3.11/site-packages/kr8s/_api.py:267: UserWarning: Server error '503 Service Unavailable' for url 'https://35.189.1.155/apis/tap.linkerd.io/v1alpha1'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
  warnings.warn(str(e))
```

**Comment by stanislavhordiyenko** [comment]
Script completed successfully, thank you @jacobtomlinson . Much appreciated. That was a quick fix :-)

**Comment by jacobtomlinson** [comment]
Sweet, glad that worked. Let me merge and release so you can move back off the dev branch.

**Comment by jacobtomlinson** [comment]
@stanislavhordiyenko `0.12.4` is now on PyPI with this fix in.

If you have a minute I'd love to hear a little more about what you're using `kr8s` for. Knowing what problems people are trying to solve, and why they chose `kr8s` over other Python libraries or `kubectl` really helps me build out examples, docs and generally prioritise work here.

**Comment by stanislavhordiyenko** [comment]
Much appreciated.

**Comment by stanislavhordiyenko** [comment]
Where do you want me to write the feedback? I am glad to share what I am using it for and my plans for the future.
