### ISSUE TITLE
kr8s failing to authenticate with valid kubeconfig file

### ISSUE THREAD

**Issue by larsks** [kr8s-org/kr8s#233]
### Which project are you reporting a bug for?

kr8s

### What happened?

I have a valid `kubeconfig` file with which I can successfully authenticate to a local kubernetes cluster:

```
$ KUBECONFIG=kubeconfig kubectl get deploy packageserver
NAME            READY   UP-TO-DATE   AVAILABLE   AGE
packageserver   3/3     3            3           7d4h
```

Using the `kubectl-whoami` plugin:

```
$ KUBECONFIG=kubeconfig kubectl whoami
system:admin
```

The `kubeconfig` file looks like this:

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://api.cluster.example.com:6443
  name: hypershift1
contexts:
- context:
    cluster: hypershift1
    namespace: clusters-vcluster1
    user: hypershift/admin
  name: hypershift
current-context: hypershift
kind: Config
preferences: {}
users:
- name: hypershift/admin
  user:
    client-certificate-data: ...
    client-key-data: ...
```

When I use the same file with `kr8s`:

```
$ KUBECONFIG=kubeconfig python
```

It fails to authenticate:

```
Python 3.11.6 (main, Oct  3 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from kr8s.objects import Deployment
>>> Deployment.get('packageserver')
/home/example/.venv/lib/python3.11/site-packages/kr8s/_api.py:267: UserWarning: forbidden: User "system:anonymous" cannot get path "/api/"
  warnings.warn(str(e))
Traceback (most recent call last):
  File "/home/example/.venv/lib/python3.11/site-packages/kr8s/_api.py", line 136, in call_api
    response.raise_for_status()
  File "/home/example/.venv/lib/python3.11/site-packages/httpx/_models.py", line 758, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://api.hypershift1.int.massopen.cloud:6443/apis/apps/v1/namespaces/clusters-vcluster1/deployments'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/example/.venv/lib/python3.11/site-packages/kr8s/_io.py", line 75, in wrapped
    return portal.call(wrapped)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/example/.venv/lib/python3.11/site-packages/kr8s/_io.py", line 50, in call
    return self._portal.call(func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/example/.venv/lib/python3.11/site-packages/anyio/from_thread.py", line 266, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/example/.venv/lib/python3.11/site-packages/anyio/from_thread.py", line 203, in _call_func
    retval = await retval
             ^^^^^^^^^^^^
  File "/home/example/.venv/lib/python3.11/site-packages/kr8s/_objects.py", line 194, in get
    raise e
  File "/home/example/.venv/lib/python3.11/site-packages/kr8s/_objects.py", line 188, in get
    resources = await api._get(
                ^^^^^^^^^^^^^^^
  File "/home/example/.venv/lib/python3.11/site-packages/kr8s/_api.py", line 341, in _get
    async with self._get_kind(
  File "/usr/lib64/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/example/.venv/lib/python3.11/site-packages/kr8s/_api.py", line 270, in _get_kind
    async with self.call_api(
  File "/usr/lib64/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/example/.venv/lib/python3.11/site-packages/kr8s/_api.py", line 149, in call_api
    raise ServerError(
kr8s._exceptions.ServerError: deployments.apps is forbidden: User "system:anonymous" cannot list resource "deployments" in API group "apps" in the namespace "clusters-vcluster1"
```

I'm not sure why kr8s is unable to authenticate with this file when it works fine with `kubectl`.

**Comment by jacobtomlinson** [comment]
This could also be related to #234. Do you have a service account also configured via environment variables?

**Comment by larsks** [comment]
> Could you try something very minimal like the following:
>
> ```
> import kr8s
> api = kr8s.api(kubeconfig="/full/path/to/your/kubeconfig")
> api.version()

That works...

```
>>> api.version()
{'major': '1', 'minor': '27', 'gitVersion': 'v1.27.6+f67aeb3', 'gitCommit': 'f3ec0ed759cde48849b6e3117c091b7db90c95fa', 'gitTreeState': 'clean', 'buildDate': '2023-10-20T22:20:44Z', 'goVersion': 'go1.20.10 X:strictfipsruntime', 'compiler': 'gc', 'platform': 'linux/amd64'}
```

...but `api.version()` doesn't require authentication. As soon as we try to retrieve something...

```
>>> api.get('namespace')
.
.
.
kr8s._exceptions.ServerError: namespaces is forbidden: User "system:anonymous" cannot list resource "namespaces" in API group "" at the cluster scope
```

> This could also be related to #234. Do you have a service account also configured via environment variables?

I do not. Just to demonstrate, we can try things out with a sanitized environment:

```
$ env -i KUBECONFIG=$PWD/kubeconfig HOME="$HOME" PATH="$PATH" kubectl get ns
...a list of namespaces appears...
```

Vs:

```
$ env -i HOME="$HOME" PATH="$PATH" python
>>> import kr8s
>>> api = kr8s.api(kubeconfig="./kubeconfig")
>>> api.version()
{'major': '1', 'minor': '27', 'gitVersion': 'v1.27.6+f67aeb3', 'gitCommit': 'f3ec0ed759cde48849b6e3117c091b7db90c95fa', 'gitTreeState': 'clean', 'buildDate': '2023-10-20T22:20:44Z', 'goVersion': 'go1.20.10 X:strictfipsruntime', 'compiler': 'gc', 'platform': 'linux/amd64'}
>>> api.get('namespaces')
.
.
.
kr8s._exceptions.ServerError: namespaces is forbidden: User "system:anonymous" cannot list resource "namespaces" in API group "" at the cluster scope
```

**Comment by jacobtomlinson** [comment]
@larsks I just pushed `v0.12.5` which has a new `whoami()` method. It wont solve your problem here but could be useful in debugging.

Could you try running the following and see if it matches with what `kubectl whoami` reports?

```python
import kr8s
print(kr8s.api(kubeconfig="/full/path/to/your/kubeconfig").whoami())
```

**Comment by jacobtomlinson** [comment]
As there has been no update here for a month and nobody else has commented with a "me too" type message I'm going to close this out as cannot reproduce. But if you're still having trouble and you wish to continue troubleshooting just comment here and I'll reopen it.

**Comment by roxit** [comment]
I was able to reproduce the issue. When `insecure-skip-tls-verify` is true, kubectl still sends the client cert to apiserver (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/transport/transport.go#L93), while kr8s skips SSL setup completely.
