### ISSUE TITLE
Kubernetes version update script broken

### ISSUE THREAD

**Issue by jacobtomlinson** [kr8s-org/kr8s#514]
For the last few days the Kubernetes update script has been failing.

https://github.com/kr8s-org/kr8s/actions/runs/11676720158

```pytb
Traceback (most recent call last):
Loading Kubernetes versions from https://endoflife.date/api/kubernetes.json...
  File "/home/runner/work/kr8s/kr8s/./ci/update-kubernetes.py", line 200, in <module>
Loading Azure AKS versions from https://endoflife.date/api/azure-kubernetes-service.json...
    main()
  File "/home/runner/work/kr8s/kr8s/./ci/update-kubernetes.py", line 181, in main
    versions = get_versions()
               ^^^^^^^^^^^^^^
  File "/home/runner/work/kr8s/kr8s/./ci/update-kubernetes.py", line 125, in get_versions
    versions = extend_versions(oss_versions, get_azure_aks_versions(), "Azure AKS")
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/kr8s/kr8s/./ci/update-kubernetes.py", line 46, in get_azure_aks_versions
    data = [
           ^
  File "/home/runner/work/kr8s/kr8s/./ci/update-kubernetes.py", line 50, in <listcomp>
    x["eol"] if not x["lts"] else x["support"], DATE_FORMAT
                                  ~^^^^^^^^^^^
KeyError: 'support'
```

Looks like `endoflife.date` has inconsistent data for the Azure Kubernetes Service which is causing the auto update script to break.

For Kubernetes `1.27` they appear to use the `eol` field for the LTS EOL date, and the `lts` and `support` fields for the original EOL date.

```json
{
   "cycle":"1.27",
   "releaseDate":"2023-08-16",
   "eol":"2025-07-31",
   "lts":"2024-07-31",
   "link":"https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar",
   "support":"2024-07-31"
}
```

but for `1.30` they seem to use the `lts` date for the original EOL date and the `eol` field for the LTS EOL date.

```json
{
   "cycle":"1.30",
   "releaseDate":"2024-08-05",
   "eol":"2025-07-31",
   "lts":"2026-07-31",
   "link":"https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar"
}
```

**Comment by jacobtomlinson** [comment]
I've opened https://github.com/endoflife-date/endoflife.date/pull/6166 to try and resolve the inconsistency upstream.
